events {}

http {
    # include modular configs
    include /etc/nginx/conf.d/*.conf;
}

stream {
    server {
        listen 6514 ssl;
        proxy_pass wazuh-ip:514;

        ssl_certificate crt.crt;
        ssl_certificate_key key.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers DEFAULT;
    }
}
