# make gtls driver the default and set certificate files
global(
    DefaultNetstreamDriver="gtls"
    DefaultNetstreamDriverCertFile="/etc/rsyslog.d/keys/wilcard_fullchain.crt"
    DefaultNetstreamDriverKeyFile="/etc/rsyslog.d/keys/wildcard.key"
)

#ruleset 
ruleset(name="fortiappsec") {
    action(
        type="omfile"
        file="/var/log/fortiappsec.log"
    )
    stop
}

# start up listener at port 6514
input(
    type="imtcp"
    port="6514"
    StreamDriver.Name="gtls"
    StreamDriver.Mode="1"
    StreamDriver.Auwthmode="anon"
    ruleset="fortiappsec"
)
