template(name="external-tcp" type="string" string="/var/log/hosts/%fromhost-ip%.log")

ruleset(name="remote-tcp") {
    action(type="omfile" dynaFile="external-tcp")
    stop
}

input(type="imtcp" port="514" ruleset="remote-tcp")
